### PR TITLE
Fix invalid iterator

### PR DESCRIPTION
**Pull request by jrw972**

### CODE REVIEW

**Comment by jrw972** [comment]
@smnrgrs Can you test this branch so we can move the bug fix along?

**Comment by smnrgrs** [comment]
I'll try and progress this tomorrow

**Comment by smnrgrs** [comment]
@jrw972 the patch is good. I'm unsure of the workflow now - do I need to create a new PR?

**Review by smnrgrs — APPROVED** [review]

**Comment by jrw972** [comment]
@smnrgrs Merge this PR.  Then we'll switch to the PR in the OpenDDS repo.

**Comment by smnrgrs** [comment]
I appreciate your help getting this fix in.

**Comment by jrw972** [comment]
Thank you for contributing.

**Pull request merged**
